// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQXyHDpQeCJk0rJBWhlnoXQPjPaNCvfEM',
    appId: '1:1012666040892:web:6e9da502c00b17c8d93939',
    messagingSenderId: '1012666040892',
    projectId: 'smartstove',
    authDomain: 'smartstove-2fcbe.firebaseapp.com',
    storageBucket: 'smartstove.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsN9aSJy6p8b-Cb9XHlNXOMGk-1SCmKFg',
    appId: '1:1012666040892:android:46a686c874b03b43d93939',
    messagingSenderId: '1012666040892',
    projectId: 'smartstove',
    storageBucket: 'smartstove.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE0YaOIxpj0hlWqyf4kpPlGGhiaM_LRAY',
    appId: '1:1012666040892:ios:f462648a7fff3098d93939',
    messagingSenderId: '1012666040892',
    projectId: 'smartstove',
    storageBucket: 'smartstove.appspot.com',
    iosClientId: '1012666040892-e706tgtba8h0udku9qpoa22vik0gpv0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE0YaOIxpj0hlWqyf4kpPlGGhiaM_LRAY',
    appId: '1:1012666040892:ios:f462648a7fff3098d93939',
    messagingSenderId: '1012666040892',
    projectId: 'smartstove',
    storageBucket: 'smartstove.appspot.com',
    iosClientId: '1012666040892-e706tgtba8h0udku9qpoa22vik0gpv0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
